### ISSUE TITLE
cfops restore issues 

### ISSUE THREAD

**Issue by sudhindrarao** [pivotalservices/cfops#64] opened 2016-03-23 21:17 UTC
we tested cfops restore.  Restored opsmgr and ER from backup that we took using cfops backup successfully,  however we found this test case which did not quite work :   Here are the steps to reproduce this scenario :  
1. OpsMgr:  Added /deployed RabbitMQ tile 
2. ER :  Increased etcd and cc worker nodes
2. Ran cfops restore on Opsmgr
    >> We saw RabbitMQ tile disappeared, however we noticed that 
    >> rabbitmq nodes were still running (bosh vms command)
3. Ran cfops restore on ER
    >> ops manager ER resource config showed original numbers of nodes for etcd, cc workers
    >>saw etdc, cc workers nodes were still running
    
Understand opsmgr, bosh state disconnect.. but reverting back to 
if we need to take the backup of bosh db and its state.. may be a gap here..

**Comment by xchapter7x** [comment] 2016-04-04 15:04
duplicate of https://github.com/pivotalservices/cfops/issues/61

this issue should now be resolved

**Closed by xchapter7x** 2016-04-04 15:04 UTC
